;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,245,204
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env21
	.byte $00
	.byte $70 ;instrument $02
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env10,@env18,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env12,@env19,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env17,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env14,@env0,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env6,@env0,@env22
	.byte $00
	.byte $70 ;instrument $09
	.word @env7,@env0,@env22
	.byte $00
	.byte $70 ;instrument $0c
	.word @env15,@env20,@env0
	.byte $00
	.byte $70 ;instrument $0d
	.word @env16,@env20,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env4,@env19,@env0
	.byte $00
	.byte $b0 ;instrument $16
	.word @env11,@env0,@env0
	.byte $00
	.byte $30 ;instrument $18
	.word @env13,@env18,@env0
	.byte $00
	.byte $70 ;instrument $19
	.word @env2,@env18,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c3,$00,$00
@env2:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c1,$00,$07
@env3:
	.byte $ce,$00,$00
@env4:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env5:
	.byte $cb,$ca,$c8,$c7,$c5,$c4,$c3,$c1,$c0,$00,$08
@env6:
	.byte $cc,$cb,$ca,$ca,$c9,$03,$c8,$03,$c7,$07,$c6,$08,$c5,$0a,$c4,$0c
	.byte $c3,$0c,$c2,$12,$c1,$19,$c0,$00,$16
@env7:
	.byte $c2,$02,$c1,$05,$c0,$03,$c1,$03,$c2,$c1,$09,$c0,$05,$c1,$0c,$c0
	.byte $00,$0f
@env8:
	.byte $c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
@env9:
	.byte $c9,$07,$c6,$05,$c9,$07,$c9,$00,$06
@env10:
	.byte $c7,$00,$00
@env11:
	.byte $c1,$c3,$c4,$c6,$c7,$c8,$c9,$ca,$ca,$cb,$cc,$cc,$cd,$0d,$cc,$cc
	.byte $cb,$ca,$c7,$c1,$00,$13
@env12:
	.byte $cd,$cb,$c9,$c8,$c5,$c3,$c1,$c0,$00,$07
@env13:
	.byte $cf,$00,$00
@env14:
	.byte $c7,$c2,$c0,$00,$02
@env15:
	.byte $c1,$04,$c2,$c1,$04,$c2,$c1,$00,$06
@env16:
	.byte $c2,$08,$c1,$c1,$c1,$00,$04
@env17:
	.byte $cc,$ca,$c8,$c6,$c4,$c3,$c2,$c1,$c0,$00,$08
@env18:
	.byte $cc,$c0,$00,$01
@env19:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env20:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env21:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02
@env22:
	.byte $c0,$0f,$c1,$02,$c2,$02,$c1,$02,$c0,$c0,$c0,$00,$02


@song0ch0:
	.byte $fb,$09
@song0ch0loop:
@ref0:
	.byte $a2,$59,$58,$52,$83,$58,$98,$58,$a2,$58,$52,$83,$59,$58,$53,$52
	.byte $4e,$98,$4e
@ref1:
	.byte $a2,$4e,$52,$83,$52,$54,$58,$54,$8f,$4b,$4a,$81
@ref2:
	.byte $59,$58,$52,$83,$58,$98,$58,$a2,$58,$52,$83,$59,$58,$53,$52,$4e
	.byte $98,$4e
	.byte $ff,$0b
	.word @ref1
@ref4:
	.byte $a0,$40,$44,$40,$4a,$4e,$58,$54,$52,$4a,$4f,$52,$40,$44,$40,$4a
	.byte $4e,$58,$54,$52
@ref5:
	.byte $4a,$4f,$4a,$97,$5d,$58,$81
@ref6:
	.byte $40,$44,$40,$4a,$4e,$58,$54,$52,$4a,$4f,$52,$40,$44,$40,$4a,$4e
	.byte $58,$54,$52
	.byte $ff,$07
	.word @ref5
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $98,$3a,$83,$32,$83,$28,$83,$32,$83,$3a,$83,$32,$83,$28,$81
@ref9:
	.byte $81,$32,$83,$36,$83,$2c,$83,$36,$83,$24,$83,$24,$83,$32
@ref10:
	.byte $3a,$83,$32,$83,$28,$83,$32,$83,$3a,$83,$32,$83,$28,$81
	.byte $ff,$0e
	.word @ref9
@ref12:
	.byte $4a,$52,$58,$4a,$52,$58,$4a,$52,$58,$4a,$52,$58,$4e,$54,$5c,$4e
	.byte $54,$5c,$4e,$54
@ref13:
	.byte $5c,$4e,$54,$5c,$4a,$54,$5c,$4a,$54,$5c,$4a,$54,$5c,$4a,$54,$5c
	.byte $4e,$58,$60,$4e
	.byte $ff,$14
	.word @ref12
	.byte $ff,$14
	.word @ref13
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $96,$1a,$83,$1a,$83,$1a,$83,$28,$24,$22,$1a,$83,$1a,$83,$1a,$81
@ref17:
	.byte $81,$28,$24,$22,$1e,$83,$1e,$83,$1e,$83,$28,$24,$22,$24,$83,$24
@ref18:
	.byte $1a,$83,$1a,$83,$1a,$83,$28,$24,$22,$1a,$83,$1a,$83,$1a,$81
	.byte $ff,$10
	.word @ref17
@ref20:
	.byte $1a,$1a,$1a,$1a,$1a,$1a,$1a,$1a,$1a,$1a,$1a,$1a,$1e,$1e,$1e,$1e
	.byte $1e,$1e,$1e,$1e
@ref21:
	.byte $1e,$1e,$1e,$1e,$24,$24,$24,$24,$24,$24,$24,$24,$24,$24,$24,$24
	.byte $28,$28,$28,$28
	.byte $ff,$14
	.word @ref20
	.byte $ff,$14
	.word @ref21
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $96,$21,$20,$9c,$21,$96,$20,$20,$20,$20,$9c,$21,$96,$20,$21,$20
	.byte $9c,$21,$96,$20,$20,$20
@ref25:
	.byte $20,$9c,$20,$20,$20,$96,$21,$20,$9c,$21,$96,$20,$20,$20,$20,$9c
	.byte $21,$96,$20,$21,$20,$9c,$20
	.byte $ff,$0f
	.word @ref24
	.byte $ff,$10
	.word @ref25
	.byte $ff,$0f
	.word @ref24
	.byte $ff,$10
	.word @ref25
	.byte $ff,$0f
	.word @ref24
	.byte $ff,$10
	.word @ref25
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $a7
@ref33:
	.byte $a7
@ref34:
	.byte $a7
@ref35:
	.byte $a7
@ref36:
	.byte $a7
@ref37:
	.byte $a7
@ref38:
	.byte $a7
@ref39:
	.byte $a7
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$04
@song1ch0loop:
@ref40:
	.byte $92,$45,$94,$45,$92,$44,$85,$90,$44,$85,$3e,$8d,$92,$44,$85,$45
	.byte $45,$90,$3e,$85
@ref41:
	.byte $92,$3f,$94,$3f,$92,$3e,$85,$90,$3e,$85,$3e,$85,$3a,$85,$92,$3e
	.byte $85,$3f,$3f,$90,$3e,$85
	.byte $ff,$0e
	.word @ref40
	.byte $ff,$10
	.word @ref41
@ref44:
	.byte $01,$36,$85,$36,$85,$3a,$85,$3e,$8d,$3e,$85,$3a,$85,$36,$81
@ref45:
	.byte $83,$3a,$85,$3a,$85,$3e,$85,$42,$8d,$48,$85,$44,$85,$3e,$81
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref46:
	.byte $8e,$44,$8d,$3e,$8d,$3a,$85,$3e,$85,$3e,$85,$3a,$85
@ref47:
	.byte $87,$3e,$85,$3e,$85,$3a,$85,$44,$85,$44,$85,$3e,$85,$44,$85
@ref48:
	.byte $44,$8d,$3e,$8d,$3a,$85,$3e,$85,$3e,$85,$3a,$85
	.byte $ff,$0f
	.word @ref47
@ref50:
	.byte $36,$85,$36,$85,$3a,$85,$3e,$8d,$3e,$85,$3a,$85,$36,$85
@ref51:
	.byte $3a,$85,$3a,$85,$3e,$85,$42,$8d,$48,$85,$44,$85,$3e,$85
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref52:
	.byte $80,$2d,$01,$45,$2d,$2d,$45,$01,$2d,$01,$2d,$45,$2d,$2d,$45,$2d
	.byte $44,$81
@ref53:
	.byte $27,$01,$3f,$27,$27,$3f,$01,$27,$01,$27,$3f,$27,$27,$3f,$27,$3e
	.byte $81
@ref54:
	.byte $2d,$01,$45,$2d,$2d,$45,$01,$2d,$01,$2d,$45,$2d,$2d,$45,$2d,$44
	.byte $81
	.byte $ff,$11
	.word @ref53
@ref56:
	.byte $1f,$01,$37,$1f,$1f,$37,$01,$1f,$01,$1f,$37,$1f,$1f,$37,$1f,$36
	.byte $81
@ref57:
	.byte $23,$01,$3b,$23,$23,$3b,$01,$23,$01,$23,$3b,$23,$23,$3b,$23,$3a
	.byte $81
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref58:
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$21,$21,$88,$21,$8c,$1f,$8a
	.byte $21,$21,$88,$21,$8a,$21,$8c,$1b,$8a,$21,$88,$21,$8c,$1a,$81
@ref59:
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$21,$21,$88,$21,$8a,$21,$21
	.byte $88,$21,$21,$8a,$21,$88,$21,$21,$21,$20,$81
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref59
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref59
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$04
@song2ch0loop:
@ref70:
	.byte $92,$3d,$94,$3d,$92,$3d,$94,$3d,$90,$3c,$8d,$92,$39,$94,$39,$92
	.byte $39,$94,$39,$90,$38,$8d
@ref71:
	.byte $92,$35,$94,$35,$92,$35,$94,$35,$90,$34,$8d,$92,$39,$94,$39,$92
	.byte $39,$94,$39,$90,$38,$89,$3c,$81
@ref72:
	.byte $92,$39,$94,$39,$92,$39,$94,$39,$90,$38,$8d,$92,$35,$94,$35,$92
	.byte $35,$94,$35,$90,$34,$89,$34,$81
@ref73:
	.byte $92,$33,$94,$33,$92,$33,$94,$33,$90,$32,$89,$33,$92,$35,$94,$35
	.byte $92,$35,$94,$34,$89,$90,$38,$85
@ref74:
	.byte $82,$3c,$8d,$38,$8d,$3d,$42,$85,$46,$89,$42,$85
@ref75:
	.byte $3c,$8d,$38,$8d,$3d,$42,$85,$46,$89,$4a,$85
@ref76:
	.byte $4a,$9d,$40,$89,$42,$89,$40,$85
	.byte $ff,$08
	.word @ref76
@ref78:
	.byte $86,$55,$4b,$55,$4b,$55,$4b,$55,$4b,$5b,$51,$5b,$51,$5b,$51,$5b
	.byte $50,$81
@ref79:
	.byte $5f,$55,$5f,$55,$5f,$55,$5f,$55,$63,$59,$63,$59,$63,$59,$69,$6c
	.byte $81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref80:
	.byte $8e,$3c,$9d,$38,$9d
@ref81:
	.byte $34,$9d,$38,$95,$3c,$85
@ref82:
	.byte $38,$9d,$34,$95,$34,$85
@ref83:
	.byte $32,$95,$32,$85,$34,$8d,$38,$8d
@ref84:
	.byte $84,$3c,$8d,$38,$8d,$3d,$42,$85,$46,$89,$42,$85
	.byte $ff,$0b
	.word @ref75
	.byte $ff,$08
	.word @ref76
	.byte $ff,$08
	.word @ref76
@ref88:
	.byte $4a,$85,$4c,$85,$4a,$46,$4a,$89,$46,$8d,$42,$8d
@ref89:
	.byte $4a,$85,$4c,$85,$4a,$46,$4c,$89,$4a,$8d,$50,$85,$54,$85
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref90:
	.byte $80,$3d,$01,$39,$3d,$01,$3d,$01,$3d,$01,$39,$01,$3d,$4b,$39,$47
	.byte $3c,$81
@ref91:
	.byte $3d,$01,$39,$3d,$01,$3d,$01,$3d,$01,$39,$01,$3d,$4b,$39,$47,$3c
	.byte $81
@ref92:
	.byte $39,$01,$35,$39,$01,$39,$01,$39,$01,$35,$01,$39,$47,$35,$43,$38
	.byte $81
	.byte $ff,$11
	.word @ref92
@ref94:
	.byte $3d,$3d,$55,$3d,$3d,$55,$3d,$55,$39,$39,$51,$39,$39,$51,$39,$50
	.byte $81
@ref95:
	.byte $35,$35,$4d,$35,$35,$4d,$35,$4d,$33,$33,$4b,$33,$33,$4b,$33,$4a
	.byte $81
	.byte $ff,$11
	.word @ref94
	.byte $ff,$11
	.word @ref95
@ref98:
	.byte $3d,$3d,$55,$3d,$3d,$55,$3d,$55,$43,$43,$5b,$43,$43,$5b,$43,$5a
	.byte $81
@ref99:
	.byte $47,$47,$5f,$47,$47,$5f,$47,$5f,$4b,$4b,$63,$4b,$4b,$63,$4b,$62
	.byte $81
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref59
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref59
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref59
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref59
	.byte $ff,$11
	.word @ref58
	.byte $ff,$11
	.word @ref59
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref110:
	.byte $bf
@ref111:
	.byte $bf
@ref112:
	.byte $bf
@ref113:
	.byte $bf
@ref114:
	.byte $bf
@ref115:
	.byte $bf
@ref116:
	.byte $bf
@ref117:
	.byte $bf
@ref118:
	.byte $bf
@ref119:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@ref120:
	.byte $92,$45,$94,$45,$92,$45,$90,$44,$87,$45,$40,$83,$92,$45,$94,$45
	.byte $92,$45,$90,$41,$44,$8d
@song3ch0loop:
@ref121:
	.byte $00
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref122:
	.byte $8e,$45,$01,$44,$85,$01,$45,$40,$85,$45,$45,$41,$44,$91
@song3ch1loop:
@ref123:
	.byte $00
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref124:
	.byte $80,$2d,$2d,$45,$41,$2d,$2d,$45,$4d,$45,$45,$41,$44,$91
@song3ch2loop:
@ref125:
	.byte $00
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref126:
	.byte $8a,$21,$21,$88,$21,$8c,$1b,$1f,$8a,$21,$88,$21,$8a,$21,$88,$21
	.byte $21,$8a,$21,$88,$20,$91
@song3ch3loop:
@ref127:
	.byte $81
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref128:
	.byte $bf
@song3ch4loop:
@ref129:
	.byte $81
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$06
@ref130:
	.byte $98,$61,$5d,$59,$53,$5d,$59,$55,$4f,$52,$9d
@song4ch0loop:
@ref131:
	.byte $81
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@ref132:
	.byte $98,$1f,$1f,$1f,$1f,$25,$25,$25,$25,$28,$9d
@song4ch1loop:
@ref133:
	.byte $81
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@ref134:
	.byte $9e,$1e,$8d,$24,$8d,$96,$22,$85,$22,$85,$22,$8d
@song4ch2loop:
@ref135:
	.byte $81
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@ref136:
	.byte $96,$21,$21,$9c,$21,$21,$9a,$21,$21,$9c,$21,$98,$21,$9c,$04,$9d
@song4ch3loop:
@ref137:
	.byte $81
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@ref138:
	.byte $bf
@song4ch4loop:
@ref139:
	.byte $81
	.byte $fd
	.word @song4ch4loop
